# Generated by Django 6.0.7 on 2026-09-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_devise_benin', models.ImageField(blank=True, null=True, upload_to='platform_admin/branding/', verbose_name='Logo de la devise du Bénin (Fraternité-Justice-Travail)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages graphiques de la plateforme',
                'verbose_name_plural': 'Réglages graphiques de la plateforme',
            },
        ),
    ]
