# Generated by Django 6.0.7 on 2026-09-01 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0005_classe_school_alter_classe_nom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee', models.PositiveIntegerField()),
                ('fichier', models.FileField(upload_to='banque/documents/')),
                ('is_payant', models.BooleanField(default=False, verbose_name='Payant')),
                ('prix', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_banque', to='classes.classe')),
            ],
            options={
                'ordering': ['-annee', 'classe'],
            },
        ),
        migrations.CreateModel(
            name='EpreuveClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee', models.PositiveIntegerField()),
                ('fichier_sujet', models.FileField(upload_to='banque/epreuves/sujets/')),
                ('fichier_corrige', models.FileField(blank=True, null=True, upload_to='banque/epreuves/corriges/')),
                ('is_payant', models.BooleanField(default=False, verbose_name='Payant')),
                ('prix', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves_banque', to='classes.classe')),
            ],
            options={
                'ordering': ['-annee', 'classe'],
            },
        ),
    ]
