# Generated by Django 6.0.7 on 2026-07-29 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_etablissement', models.CharField(max_length=20, unique=True, verbose_name='Code établissement')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('sigle', models.CharField(blank=True, max_length=30, verbose_name='Sigle')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('type_etablissement', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé')], default='prive', max_length=20, verbose_name='Type')),
                ('devise', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuration/logo/')),
                ('photo_couverture', models.ImageField(blank=True, null=True, upload_to='configuration/couverture/')),
                ('description', models.TextField(blank=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Bénin', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('subdomain', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='Africa/Porto-Novo', max_length=100)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('numero_autorisation', models.CharField(blank=True, max_length=100)),
                ('ifu', models.CharField(blank=True, max_length=100, verbose_name='IFU / NIF')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Fonction')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='configuration.schoolprofile', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('school', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='configuration/staff/signatures/', verbose_name='Signature')),
                ('ordre_signature', models.PositiveIntegerField(default=1, verbose_name='Ordre de signature')),
                ('afficher_signature', models.BooleanField(default=True, verbose_name='Afficher la signature')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='configuration.schoolprofile', verbose_name='Établissement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_staff', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='configuration.staffrole', verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['ordre_signature', 'role'],
            },
        ),
    ]
