# Generated by Django 6.0.7 on 2026-09-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='cachet',
            field=models.ImageField(blank=True, null=True, upload_to='configuration/cachets/', verbose_name="Cachet / Tampon de l'établissement"),
        ),
    ]
