# Generated by Django 6.0.7 on 2026-09-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_schoolprofile_cachet'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut de validation'),
        ),
    ]
