# Generated by Django 6.0.7 on 2026-08-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_eleve_options_eleve_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Matricule'),
        ),
    ]
