# Generated by Django 6.0.7 on 2026-09-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_eleve_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='npi',
            field=models.CharField(blank=True, max_length=20, verbose_name='NPI'),
        ),
    ]
