# Generated by Django 6.0.7 on 2026-09-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_eleve_npi'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('ancien', 'Ancien')], default='nouveau', max_length=10, verbose_name='Statut'),
        ),
    ]
