# Generated by Django 6.0.7 on 2026-09-10 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_eleve_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='code_parent',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code de liaison parent'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='enfants', to=settings.AUTH_USER_MODEL, verbose_name='Parents'),
        ),
    ]
