# Generated by Django 6.0.7 on 2026-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classe_nom'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(blank=True, to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
