# Generated by Django 6.0.7 on 2026-08-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classe_nom'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='configuration.schoolprofile', verbose_name='Établissement'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=58),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('school', 'nom')},
        ),
    ]
