# Generated by Django 6.0.7 on 2026-09-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classe_school_alter_classe_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='couleur_bulletin',
            field=models.CharField(choices=[('bleu', 'Bleu'), ('orange', 'Orange'), ('rouge', 'Rouge'), ('vert', 'Vert'), ('violet', 'Violet'), ('noir', 'Noir')], default='bleu', max_length=20, verbose_name='Couleur du bulletin'),
        ),
        migrations.AddField(
            model_name='classe',
            name='style_bordure',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Simple'), (2, 'Double trait'), (3, 'En creux (groove)'), (4, 'En relief (ridge)')], default=1, verbose_name='Style de bordure du bulletin'),
        ),
    ]
