# Generated by Django 6.0.7 on 2026-09-09 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classe_couleur_bulletin_classe_style_bordure'),
        ('teachers', '0003_remove_teacher_school_alter_teacher_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='teachers.teacher', verbose_name='Professeur Principal'),
        ),
    ]
