# Generated by Django 6.0.7 on 2026-08-19 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('CELTIS', 'Celtiis Cash'), ('MOOV', 'Moov Money')], max_length=10, unique=True)),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de réception')),
                ('actif', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('operateur', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('CELTIS', 'Celtiis Cash'), ('MOOV', 'Moov Money')], max_length=10)),
                ('numero_reception', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('reference_paiement', models.CharField(max_length=100, verbose_name='Référence / ID de la transaction reçue par SMS')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('note_admin', models.CharField(blank=True, max_length=255)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
