# Generated by Django 6.0.7 on 2026-07-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Enseignant'), ('admin', 'Administrateur')], default='student', max_length=20),
        ),
    ]
