# Generated by Django 6.0.7 on 2026-08-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_deleted_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Élève'), ('teacher', 'Enseignant'), ('parent', 'Parent'), ('staff', 'Personnel administratif'), ('admin', 'Administrateur général')], default='student', max_length=20, verbose_name='Rôle'),
        ),
    ]
