# Generated by Django 6.0.7 on 2026-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('superieur', 'Supérieur'), ('concours', 'Concours professionnel')], max_length=20, verbose_name="Niveau d'étude"),
        ),
    ]
