# Generated by Django 6.0.7 on 2026-08-13 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classe_school_alter_classe_nom_and_more'),
        ('configuration', '0001_initial'),
        ('subjects', '0002_alter_subject_options_remove_subject_desciptioon_and_more'),
        ('teachers', '0002_teacher_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='classes.classe'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='subjects.subject'),
        ),
        migrations.CreateModel(
            name='TeacherSchoolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=6, verbose_name='Code PIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_access', to='configuration.schoolprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_access', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'school')},
            },
        ),
    ]
