# Generated by Django 6.0.7 on 2026-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix (FCFA)'),
        ),
    ]
