# Generated by Django 6.0.7 on 2026-08-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentcollection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
