# Generated by Django 6.0.7 on 2026-08-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0002_epreuveexamen_is_payant_epreuveexamen_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuveexamen',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epreuveexamen',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
