# Generated by Django 6.0.7 on 2026-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examens', '0003_epreuveexamen_deleted_at_epreuveexamen_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuveexamen',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
