# Generated by Django 6.0.7 on 2026-09-10 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeMaitreEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contact', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone_contact', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='Email (optionnel)')),
                ('matiere', models.CharField(max_length=100, verbose_name='Matière')),
                ('classe_enfant', models.CharField(max_length=50, verbose_name="Classe de l'enfant")),
                ('zone', models.CharField(max_length=150, verbose_name='Zone / Quartier')),
                ('college_enfant', models.CharField(blank=True, max_length=200, verbose_name="Collège / École de l'enfant")),
                ('niveau_professeur_voulu', models.CharField(blank=True, max_length=100, verbose_name='Niveau du professeur souhaité')),
                ('message', models.TextField(blank=True, verbose_name='Informations complémentaires')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_discussion', 'En discussion'), ('rdv_planifie', 'Rendez-vous planifié'), ('cloturee', 'Clôturée')], default='nouvelle', max_length=20)),
                ('rdv_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du rendez-vous')),
                ('rdv_lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu / Moyen du rendez-vous')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_maitre_etude', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande de maître d'étude",
                'verbose_name_plural': "Demandes de maître d'étude",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_demande_maitre_etude', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='repetition.demandemaitreetude')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
