# Generated by Django 6.0.7 on 2026-09-11 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandemaitreetude',
            name='code_suivi',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='Code de suivi'),
        ),
        migrations.AddField(
            model_name='messagedemande',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagedemande',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_demande_maitre_etude', to=settings.AUTH_USER_MODEL),
        ),
    ]
