# Generated by Django 6.0.7 on 2026-08-16 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Concours',
                'verbose_name_plural': 'Concours',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EpreuveConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('annee', models.PositiveIntegerField()),
                ('fichier_sujet', models.FileField(upload_to='concours/sujets/')),
                ('fichier_corrige', models.FileField(blank=True, null=True, upload_to='concours/corriges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='concours.concours')),
            ],
            options={
                'ordering': ['-annee', 'concours'],
            },
        ),
    ]
