# Generated by Django 6.0.7 on 2026-08-25 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0003_epreuveconcours_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epreuveconcours',
            options={'ordering': ['-annee', 'concours', 'titre'], 'verbose_name': 'Épreuve de concours', 'verbose_name_plural': 'Épreuves de concours'},
        ),
        migrations.AddField(
            model_name='epreuveconcours',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='concours',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='concours',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du concours'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves_concours_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='annee',
            field=models.PositiveIntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='concours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='concours.concours', verbose_name='Concours'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='fichier_corrige',
            field=models.FileField(blank=True, null=True, upload_to='concours/corriges/', verbose_name='Corrigé'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='fichier_sujet',
            field=models.FileField(upload_to='concours/sujets/', verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='titre',
            field=models.CharField(max_length=200, verbose_name="Titre de l'épreuve"),
        ),
    ]
