# Generated by Django 6.0.7 on 2026-08-25 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0004_alter_epreuveconcours_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epreuveconcours',
            options={'ordering': ['-annee', 'concours']},
        ),
        migrations.RemoveField(
            model_name='epreuveconcours',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='concours',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='concours',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='ajoute_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='annee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='concours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='concours.concours'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='fichier_corrige',
            field=models.FileField(blank=True, null=True, upload_to='concours/corriges/'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='fichier_sujet',
            field=models.FileField(upload_to='concours/sujets/'),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epreuveconcours',
            name='titre',
            field=models.CharField(max_length=200),
        ),
    ]
