# Generated by Django 6.0.7 on 2026-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concours', '0005_alter_epreuveconcours_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuveconcours',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
