# Generated by Django 6.0.7 on 2026-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['nom'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='desciptioon',
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
