# Generated by Django 6.0.7 on 2026-09-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_options_remove_subject_desciptioon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='categorie',
            field=models.CharField(blank=True, choices=[('scientifique', 'Scientifique'), ('litteraire', 'Littéraire')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
